//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public int Ida { get; set; }
        public int fk_User { get; set; }
        public System.DateTime employmentDate { get; set; }
        public decimal salary { get; set; }
    
        public virtual User User { get; set; }
    }
}
