//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int Id { get; set; }
        public int fk_customer { get; set; }
        public string customerFI { get; set; }
        public System.DateTime date { get; set; }
        public int fk_cadastralObject { get; set; }
        public string cadastralObject { get; set; }
        public int fk_typeCW { get; set; }
        public string typeCW { get; set; }
        public string description { get; set; }
        public int fk_status { get; set; }
        public string status { get; set; }


        public virtual CadastralObject CadastralObject { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Status Status { get; set; }
        public virtual TypeCW TypeCW { get; set; }
    }
}
