//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastralWork
    {
        public int Id { get; set; }
        public int fk_typeCW { get; set; }
        public int fk_Application { get; set; }
        public int fk_engineer { get; set; }
        public string accounting { get; set; }
        public string description { get; set; }
        public decimal cost { get; set; }
    
        public virtual Engineer Engineer { get; set; }
        public virtual TypeCW TypeCW { get; set; }
    }
}
