//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class CadastralObject
    {          
        [Key]
        public int Id { get; set; }
        [ForeignKey(nameof(HandBookOfCOType))]
        public int? fk_typeCO { get; set; }
        public string cadastralNumber { get; set; }
        public System.DateTime dateOfEntry { get; set; }
        public string legalStatus { get; set; }
        public string address { get; set; }
        public string preview { get; set; }
        public string subPreview { get; set; }
        public double square { get; set; }
        public decimal cost { get; set; }        

        [InverseProperty(nameof(Application.CadastralObject))]
        public virtual ICollection<Application> Applications { get; set; } = new HashSet<Application>();
        public virtual HandBookOfCOType HandBookOfCOType { get; set; }
    }
}
