//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer : User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Application = new HashSet<Application>();
        }
    
        public int Idc { get; set; }
        public string placeWork { get; set; }
        public string applications { get; set; }
        public Customer(string surnameName, string name, string patronimic, string placeWork,  string applications) 
            : base(surnameName, name, patronimic)
        {
            this.surnameName = surnameName;
            this.name = name;
            this.patronimic = patronimic;
            this.placeWork = placeWork;
            this.applications = applications;
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Application { get; set; }
    }
}
