//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMEntities : DbContext
    {
        public CMEntities()
            : base("name=CMEntities")
        {  }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrator { get; set; }
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<CadastralObject> CadastralObject { get; set; }
        public virtual DbSet<CadastralWork> CadastralWork { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Engineer> Engineer { get; set; }
        public virtual DbSet<HandBookOfCOTypes> HandBookOfCOTypes { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Table> Table { get; set; }
        public virtual DbSet<TypeCW> TypeCW { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
