//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMEntities : DbContext
    {
        public CMEntities()
            : base("name=Cadastral_ManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<CadastralObject> CadastralObjects { get; set; }
        public virtual DbSet<CadastralWork> CadastralWorks { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Engineer> Engineers { get; set; }
        public virtual DbSet<HandBookOfCOType> typeCOs { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<TypeCW> TypeCWs { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
